//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ServiceModel;

namespace Servicios.QuotationMilenioLiberty {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://libertytypes.com.iaxis.services", ConfigurationName="QuotationMilenioLiberty.QuotationCarGenericPortType", ProtectionLevel = System.Net.Security.ProtectionLevel.EncryptAndSign)]
    public interface QuotationCarGenericPortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://libertytypes.com.iaxis.services/QuotationCarGenericPortType/quotationCarGe" +
            "nericRequest", ReplyAction="http://libertytypes.com.iaxis.services/QuotationCarGenericPortType/quotationCarGe" +
            "nericResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Persona))]
        Servicios.QuotationMilenioLiberty.quotationCarGenericResponse quotationCarGeneric(Servicios.QuotationMilenioLiberty.quotationCarGenericRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://libertytypes.com.iaxis.services/QuotationCarGenericPortType/quotationCarGe" +
            "nericRequest", ReplyAction="http://libertytypes.com.iaxis.services/QuotationCarGenericPortType/quotationCarGe" +
            "nericResponse")]
        System.Threading.Tasks.Task<Servicios.QuotationMilenioLiberty.quotationCarGenericResponse> quotationCarGenericAsync(Servicios.QuotationMilenioLiberty.quotationCarGenericRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://libertytypes.com.iaxis.services")]
    public partial class Amparo : ElementoCodificado {
        
        private string capitalField;
        
        private bool obligatorioField;
        
        private bool obligatorioFieldSpecified;
        
        private string primaTarifaField;
        
        private string primaAnualField;
        
        private string deducibleField;
        
        private PreguntaGeneral[] preguntaAmparoField;
        
        private PreguntaTablaGeneral[] preguntaTablaAmparoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string capital {
            get {
                return this.capitalField;
            }
            set {
                this.capitalField = value;
                this.RaisePropertyChanged("capital");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool obligatorio {
            get {
                return this.obligatorioField;
            }
            set {
                this.obligatorioField = value;
                this.RaisePropertyChanged("obligatorio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool obligatorioSpecified {
            get {
                return this.obligatorioFieldSpecified;
            }
            set {
                this.obligatorioFieldSpecified = value;
                this.RaisePropertyChanged("obligatorioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string primaTarifa {
            get {
                return this.primaTarifaField;
            }
            set {
                this.primaTarifaField = value;
                this.RaisePropertyChanged("primaTarifa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string primaAnual {
            get {
                return this.primaAnualField;
            }
            set {
                this.primaAnualField = value;
                this.RaisePropertyChanged("primaAnual");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string deducible {
            get {
                return this.deducibleField;
            }
            set {
                this.deducibleField = value;
                this.RaisePropertyChanged("deducible");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("preguntaAmparo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public PreguntaGeneral[] preguntaAmparo {
            get {
                return this.preguntaAmparoField;
            }
            set {
                this.preguntaAmparoField = value;
                this.RaisePropertyChanged("preguntaAmparo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("preguntaTablaAmparo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public PreguntaTablaGeneral[] preguntaTablaAmparo {
            get {
                return this.preguntaTablaAmparoField;
            }
            set {
                this.preguntaTablaAmparoField = value;
                this.RaisePropertyChanged("preguntaTablaAmparo");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://libertytypes.com.iaxis.services")]
    public partial class PreguntaGeneral : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Pregunta preguntaField;
        
        private Respuesta respuestaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Pregunta pregunta {
            get {
                return this.preguntaField;
            }
            set {
                this.preguntaField = value;
                this.RaisePropertyChanged("pregunta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public Respuesta respuesta {
            get {
                return this.respuestaField;
            }
            set {
                this.respuestaField = value;
                this.RaisePropertyChanged("respuesta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://libertytypes.com.iaxis.services")]
    public partial class Pregunta : ElementoCodificado {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Usuario))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Pregunta))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Amparo))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://libertytypes.com.iaxis.services")]
    public partial class ElementoCodificado : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://libertytypes.com.iaxis.services")]
    public partial class PSU : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string amparoField;
        
        private bool criticoField;
        
        private string descripcionField;
        
        private string estadoField;
        
        private System.DateTime fechaField;
        
        private int nivelField;
        
        private string riesgoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string amparo {
            get {
                return this.amparoField;
            }
            set {
                this.amparoField = value;
                this.RaisePropertyChanged("amparo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool critico {
            get {
                return this.criticoField;
            }
            set {
                this.criticoField = value;
                this.RaisePropertyChanged("critico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int nivel {
            get {
                return this.nivelField;
            }
            set {
                this.nivelField = value;
                this.RaisePropertyChanged("nivel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string riesgo {
            get {
                return this.riesgoField;
            }
            set {
                this.riesgoField = value;
                this.RaisePropertyChanged("riesgo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://libertytypes.com.iaxis.services")]
    public partial class Prima : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descuentoField;
        
        private string gastosExpedicionField;
        
        private string impuestosField;
        
        private string primaAnualField;
        
        private string primerReciboField;
        
        private string sobreprimaField;
        
        private string tarifaField;
        
        private string totalField;
        
        private string vigenciaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string descuento {
            get {
                return this.descuentoField;
            }
            set {
                this.descuentoField = value;
                this.RaisePropertyChanged("descuento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string gastosExpedicion {
            get {
                return this.gastosExpedicionField;
            }
            set {
                this.gastosExpedicionField = value;
                this.RaisePropertyChanged("gastosExpedicion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string impuestos {
            get {
                return this.impuestosField;
            }
            set {
                this.impuestosField = value;
                this.RaisePropertyChanged("impuestos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string primaAnual {
            get {
                return this.primaAnualField;
            }
            set {
                this.primaAnualField = value;
                this.RaisePropertyChanged("primaAnual");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string primerRecibo {
            get {
                return this.primerReciboField;
            }
            set {
                this.primerReciboField = value;
                this.RaisePropertyChanged("primerRecibo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string sobreprima {
            get {
                return this.sobreprimaField;
            }
            set {
                this.sobreprimaField = value;
                this.RaisePropertyChanged("sobreprima");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string tarifa {
            get {
                return this.tarifaField;
            }
            set {
                this.tarifaField = value;
                this.RaisePropertyChanged("tarifa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
                this.RaisePropertyChanged("total");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string vigencia {
            get {
                return this.vigenciaField;
            }
            set {
                this.vigenciaField = value;
                this.RaisePropertyChanged("vigencia");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://libertytypes.com.iaxis.services")]
    public partial class Estado : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoEstadoField;
        
        private string codigoEstadoServidorField;
        
        private string descripcionEstadoField;
        
        private string severidadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigoEstado {
            get {
                return this.codigoEstadoField;
            }
            set {
                this.codigoEstadoField = value;
                this.RaisePropertyChanged("codigoEstado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string codigoEstadoServidor {
            get {
                return this.codigoEstadoServidorField;
            }
            set {
                this.codigoEstadoServidorField = value;
                this.RaisePropertyChanged("codigoEstadoServidor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string descripcionEstado {
            get {
                return this.descripcionEstadoField;
            }
            set {
                this.descripcionEstadoField = value;
                this.RaisePropertyChanged("descripcionEstado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string severidad {
            get {
                return this.severidadField;
            }
            set {
                this.severidadField = value;
                this.RaisePropertyChanged("severidad");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://libertytypes.com.iaxis.services")]
    public partial class InfoResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Estado estadoField;
        
        private string requestIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Estado estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string requestID {
            get {
                return this.requestIDField;
            }
            set {
                this.requestIDField = value;
                this.RaisePropertyChanged("requestID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://libertytypes.com.iaxis.services")]
    public partial class InfoRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string aplicacionClienteField;
        
        private System.DateTime fechaField;
        
        private string ipField;
        
        private string requestIDField;
        
        private string terminalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string aplicacionCliente {
            get {
                return this.aplicacionClienteField;
            }
            set {
                this.aplicacionClienteField = value;
                this.RaisePropertyChanged("aplicacionCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ip {
            get {
                return this.ipField;
            }
            set {
                this.ipField = value;
                this.RaisePropertyChanged("ip");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string requestID {
            get {
                return this.requestIDField;
            }
            set {
                this.requestIDField = value;
                this.RaisePropertyChanged("requestID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string terminal {
            get {
                return this.terminalField;
            }
            set {
                this.terminalField = value;
                this.RaisePropertyChanged("terminal");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://libertytypes.com.iaxis.services")]
    public partial class DatosGestion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ElementoCodificado agenteField;
        
        private ElementoCodificado duracionField;
        
        private System.DateTime fechaEfectoField;
        
        private bool fechaEfectoFieldSpecified;
        
        private ElementoCodificado formaPagoField;
        
        private ElementoCodificado productoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ElementoCodificado agente {
            get {
                return this.agenteField;
            }
            set {
                this.agenteField = value;
                this.RaisePropertyChanged("agente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ElementoCodificado duracion {
            get {
                return this.duracionField;
            }
            set {
                this.duracionField = value;
                this.RaisePropertyChanged("duracion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fechaEfecto {
            get {
                return this.fechaEfectoField;
            }
            set {
                this.fechaEfectoField = value;
                this.RaisePropertyChanged("fechaEfecto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaEfectoSpecified {
            get {
                return this.fechaEfectoFieldSpecified;
            }
            set {
                this.fechaEfectoFieldSpecified = value;
                this.RaisePropertyChanged("fechaEfectoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public ElementoCodificado formaPago {
            get {
                return this.formaPagoField;
            }
            set {
                this.formaPagoField = value;
                this.RaisePropertyChanged("formaPago");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public ElementoCodificado producto {
            get {
                return this.productoField;
            }
            set {
                this.productoField = value;
                this.RaisePropertyChanged("producto");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://libertytypes.com.iaxis.services")]
    public partial class Telefono : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numeroField;
        
        private string prefijoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
                this.RaisePropertyChanged("numero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string prefijo {
            get {
                return this.prefijoField;
            }
            set {
                this.prefijoField = value;
                this.RaisePropertyChanged("prefijo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://libertytypes.com.iaxis.services")]
    public partial class Direccion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ciudadField;
        
        private string departamentoField;
        
        private string direccionField;
        
        private string paisField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ciudad {
            get {
                return this.ciudadField;
            }
            set {
                this.ciudadField = value;
                this.RaisePropertyChanged("ciudad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string departamento {
            get {
                return this.departamentoField;
            }
            set {
                this.departamentoField = value;
                this.RaisePropertyChanged("departamento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string pais {
            get {
                return this.paisField;
            }
            set {
                this.paisField = value;
                this.RaisePropertyChanged("pais");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PersonaJuridica))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PersonaNatural))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://libertytypes.com.iaxis.services")]
    public partial class Persona : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Direccion direccionField;
        
        private string numeroDocumentoField;
        
        private Telefono telefonoField;
        
        private ElementoCodificado tipoDocumentoField;
        
        private string idpersonaestField;
        
        private string idpersonarealField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Direccion direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string numeroDocumento {
            get {
                return this.numeroDocumentoField;
            }
            set {
                this.numeroDocumentoField = value;
                this.RaisePropertyChanged("numeroDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public Telefono telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public ElementoCodificado tipoDocumento {
            get {
                return this.tipoDocumentoField;
            }
            set {
                this.tipoDocumentoField = value;
                this.RaisePropertyChanged("tipoDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string idpersonaest {
            get {
                return this.idpersonaestField;
            }
            set {
                this.idpersonaestField = value;
                this.RaisePropertyChanged("idpersonaest");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string idpersonareal {
            get {
                return this.idpersonarealField;
            }
            set {
                this.idpersonarealField = value;
                this.RaisePropertyChanged("idpersonareal");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://libertytypes.com.iaxis.services")]
    public partial class PersonaJuridica : Persona {
        
        private System.DateTime fechaConstitucionField;
        
        private string razonSocialField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime fechaConstitucion {
            get {
                return this.fechaConstitucionField;
            }
            set {
                this.fechaConstitucionField = value;
                this.RaisePropertyChanged("fechaConstitucion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string razonSocial {
            get {
                return this.razonSocialField;
            }
            set {
                this.razonSocialField = value;
                this.RaisePropertyChanged("razonSocial");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://libertytypes.com.iaxis.services")]
    public partial class PersonaNatural : Persona {
        
        private System.DateTime fechaNacimientoField;
        
        private ElementoCodificado generoField;
        
        private ElementoCodificado ocupacionField;
        
        private string primerApellidoField;
        
        private string primerNombreField;
        
        private string segundoApellidoField;
        
        private string segundoNombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime fechaNacimiento {
            get {
                return this.fechaNacimientoField;
            }
            set {
                this.fechaNacimientoField = value;
                this.RaisePropertyChanged("fechaNacimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ElementoCodificado genero {
            get {
                return this.generoField;
            }
            set {
                this.generoField = value;
                this.RaisePropertyChanged("genero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public ElementoCodificado ocupacion {
            get {
                return this.ocupacionField;
            }
            set {
                this.ocupacionField = value;
                this.RaisePropertyChanged("ocupacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string primerApellido {
            get {
                return this.primerApellidoField;
            }
            set {
                this.primerApellidoField = value;
                this.RaisePropertyChanged("primerApellido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string primerNombre {
            get {
                return this.primerNombreField;
            }
            set {
                this.primerNombreField = value;
                this.RaisePropertyChanged("primerNombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string segundoApellido {
            get {
                return this.segundoApellidoField;
            }
            set {
                this.segundoApellidoField = value;
                this.RaisePropertyChanged("segundoApellido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string segundoNombre {
            get {
                return this.segundoNombreField;
            }
            set {
                this.segundoNombreField = value;
                this.RaisePropertyChanged("segundoNombre");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://libertytypes.com.iaxis.services")]
    public partial class DispositivoSeguridad : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime fechaInicioContratoField;
        
        private bool fechaInicioContratoFieldSpecified;
        
        private string numeroContratoField;
        
        private ElementoCodificado propietarioField;
        
        private ElementoCodificado tipoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime fechaInicioContrato {
            get {
                return this.fechaInicioContratoField;
            }
            set {
                this.fechaInicioContratoField = value;
                this.RaisePropertyChanged("fechaInicioContrato");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaInicioContratoSpecified {
            get {
                return this.fechaInicioContratoFieldSpecified;
            }
            set {
                this.fechaInicioContratoFieldSpecified = value;
                this.RaisePropertyChanged("fechaInicioContratoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string numeroContrato {
            get {
                return this.numeroContratoField;
            }
            set {
                this.numeroContratoField = value;
                this.RaisePropertyChanged("numeroContrato");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public ElementoCodificado propietario {
            get {
                return this.propietarioField;
            }
            set {
                this.propietarioField = value;
                this.RaisePropertyChanged("propietario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public ElementoCodificado tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://libertytypes.com.iaxis.services")]
    public partial class Accesorio : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ElementoCodificado descripcionField;
        
        private string marcaField;
        
        private ElementoCodificado tipoField;
        
        private double valorField;
        
        private bool valorFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ElementoCodificado descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string marca {
            get {
                return this.marcaField;
            }
            set {
                this.marcaField = value;
                this.RaisePropertyChanged("marca");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public ElementoCodificado tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public double valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
                this.RaisePropertyChanged("valor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valorSpecified {
            get {
                return this.valorFieldSpecified;
            }
            set {
                this.valorFieldSpecified = value;
                this.RaisePropertyChanged("valorSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://libertytypes.com.iaxis.services")]
    public partial class OtrosDatos_type0 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Accesorio[] accesorioField;
        
        private DispositivoSeguridad[] dispositivoSeguridadField;
        
        private bool nuevoField;
        
        private ElementoCodificado usoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("accesorio", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Accesorio[] accesorio {
            get {
                return this.accesorioField;
            }
            set {
                this.accesorioField = value;
                this.RaisePropertyChanged("accesorio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dispositivoSeguridad", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public DispositivoSeguridad[] dispositivoSeguridad {
            get {
                return this.dispositivoSeguridadField;
            }
            set {
                this.dispositivoSeguridadField = value;
                this.RaisePropertyChanged("dispositivoSeguridad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool nuevo {
            get {
                return this.nuevoField;
            }
            set {
                this.nuevoField = value;
                this.RaisePropertyChanged("nuevo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public ElementoCodificado uso {
            get {
                return this.usoField;
            }
            set {
                this.usoField = value;
                this.RaisePropertyChanged("uso");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://libertytypes.com.iaxis.services")]
    public partial class Placa : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string placaField;
        
        private ElementoCodificado tipoPlacaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string placa {
            get {
                return this.placaField;
            }
            set {
                this.placaField = value;
                this.RaisePropertyChanged("placa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ElementoCodificado tipoPlaca {
            get {
                return this.tipoPlacaField;
            }
            set {
                this.tipoPlacaField = value;
                this.RaisePropertyChanged("tipoPlaca");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://libertytypes.com.iaxis.services")]
    public partial class Identificacion_type0 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string chasisField;
        
        private ElementoCodificado colorField;
        
        private long kilometrajeField;
        
        private string motorField;
        
        private Placa placaField;
        
        private long valorField;
        
        private bool valorFieldSpecified;
        
        private long valorNuevoField;
        
        private bool valorNuevoFieldSpecified;
        
        private long valorActualField;
        
        private bool valorActualFieldSpecified;
        
        private long valorNuevoActualField;
        
        private bool valorNuevoActualFieldSpecified;
        
        private ElementoCodificado tipoCamperoField;
        
        private ElementoCodificado tipoCarroceriaField;
        
        private ElementoCodificado tipoPinturaField;
        
        private ElementoCodificado tipoRemolqueField;
        
        private bool transportaCombustibleField;
        
        private string vinField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string chasis {
            get {
                return this.chasisField;
            }
            set {
                this.chasisField = value;
                this.RaisePropertyChanged("chasis");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ElementoCodificado color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
                this.RaisePropertyChanged("color");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long kilometraje {
            get {
                return this.kilometrajeField;
            }
            set {
                this.kilometrajeField = value;
                this.RaisePropertyChanged("kilometraje");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string motor {
            get {
                return this.motorField;
            }
            set {
                this.motorField = value;
                this.RaisePropertyChanged("motor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public Placa placa {
            get {
                return this.placaField;
            }
            set {
                this.placaField = value;
                this.RaisePropertyChanged("placa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public long valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
                this.RaisePropertyChanged("valor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valorSpecified {
            get {
                return this.valorFieldSpecified;
            }
            set {
                this.valorFieldSpecified = value;
                this.RaisePropertyChanged("valorSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public long valorNuevo {
            get {
                return this.valorNuevoField;
            }
            set {
                this.valorNuevoField = value;
                this.RaisePropertyChanged("valorNuevo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valorNuevoSpecified {
            get {
                return this.valorNuevoFieldSpecified;
            }
            set {
                this.valorNuevoFieldSpecified = value;
                this.RaisePropertyChanged("valorNuevoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public long valorActual {
            get {
                return this.valorActualField;
            }
            set {
                this.valorActualField = value;
                this.RaisePropertyChanged("valorActual");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valorActualSpecified {
            get {
                return this.valorActualFieldSpecified;
            }
            set {
                this.valorActualFieldSpecified = value;
                this.RaisePropertyChanged("valorActualSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public long valorNuevoActual {
            get {
                return this.valorNuevoActualField;
            }
            set {
                this.valorNuevoActualField = value;
                this.RaisePropertyChanged("valorNuevoActual");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valorNuevoActualSpecified {
            get {
                return this.valorNuevoActualFieldSpecified;
            }
            set {
                this.valorNuevoActualFieldSpecified = value;
                this.RaisePropertyChanged("valorNuevoActualSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public ElementoCodificado tipoCampero {
            get {
                return this.tipoCamperoField;
            }
            set {
                this.tipoCamperoField = value;
                this.RaisePropertyChanged("tipoCampero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public ElementoCodificado tipoCarroceria {
            get {
                return this.tipoCarroceriaField;
            }
            set {
                this.tipoCarroceriaField = value;
                this.RaisePropertyChanged("tipoCarroceria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public ElementoCodificado tipoPintura {
            get {
                return this.tipoPinturaField;
            }
            set {
                this.tipoPinturaField = value;
                this.RaisePropertyChanged("tipoPintura");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public ElementoCodificado tipoRemolque {
            get {
                return this.tipoRemolqueField;
            }
            set {
                this.tipoRemolqueField = value;
                this.RaisePropertyChanged("tipoRemolque");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public bool transportaCombustible {
            get {
                return this.transportaCombustibleField;
            }
            set {
                this.transportaCombustibleField = value;
                this.RaisePropertyChanged("transportaCombustible");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string vin {
            get {
                return this.vinField;
            }
            set {
                this.vinField = value;
                this.RaisePropertyChanged("vin");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://libertytypes.com.iaxis.services")]
    public partial class Datos_type0 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoFasecoldaField;
        
        private string descripcionField;
        
        private int modeloAnyoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigoFasecolda {
            get {
                return this.codigoFasecoldaField;
            }
            set {
                this.codigoFasecoldaField = value;
                this.RaisePropertyChanged("codigoFasecolda");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int modeloAnyo {
            get {
                return this.modeloAnyoField;
            }
            set {
                this.modeloAnyoField = value;
                this.RaisePropertyChanged("modeloAnyo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://libertytypes.com.iaxis.services")]
    public partial class Automovil : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Datos_type0 datosField;
        
        private Identificacion_type0 identificacionField;
        
        private OtrosDatos_type0 otrosDatosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Datos_type0 datos {
            get {
                return this.datosField;
            }
            set {
                this.datosField = value;
                this.RaisePropertyChanged("datos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public Identificacion_type0 identificacion {
            get {
                return this.identificacionField;
            }
            set {
                this.identificacionField = value;
                this.RaisePropertyChanged("identificacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public OtrosDatos_type0 otrosDatos {
            get {
                return this.otrosDatosField;
            }
            set {
                this.otrosDatosField = value;
                this.RaisePropertyChanged("otrosDatos");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://libertytypes.com.iaxis.services")]
    public partial class PreguntaTablaGeneral : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Pregunta preguntaField;
        
        private int numeroFilaField;
        
        private int numeroColumnaField;
        
        private Respuesta respuestaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Pregunta pregunta {
            get {
                return this.preguntaField;
            }
            set {
                this.preguntaField = value;
                this.RaisePropertyChanged("pregunta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int numeroFila {
            get {
                return this.numeroFilaField;
            }
            set {
                this.numeroFilaField = value;
                this.RaisePropertyChanged("numeroFila");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int numeroColumna {
            get {
                return this.numeroColumnaField;
            }
            set {
                this.numeroColumnaField = value;
                this.RaisePropertyChanged("numeroColumna");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public Respuesta respuesta {
            get {
                return this.respuestaField;
            }
            set {
                this.respuestaField = value;
                this.RaisePropertyChanged("respuesta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://libertytypes.com.iaxis.services")]
    public partial class Respuesta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoField;
        
        private string nombreField;
        
        private string valorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
                this.RaisePropertyChanged("valor");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://libertytypes.com.iaxis.services")]
    public partial class Usuario : ElementoCodificado {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="quotationCarGenericRq", WrapperNamespace="http://libertytypes.com.iaxis.services", IsWrapped=true)]
    public partial class quotationCarGenericRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://libertytypes.com.iaxis.services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("amparo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Servicios.QuotationMilenioLiberty.Amparo[] amparo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://libertytypes.com.iaxis.services", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Servicios.QuotationMilenioLiberty.Automovil automovil;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://libertytypes.com.iaxis.services", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Servicios.QuotationMilenioLiberty.PersonaNatural conductor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://libertytypes.com.iaxis.services", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Servicios.QuotationMilenioLiberty.DatosGestion datosGestion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://libertytypes.com.iaxis.services", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Servicios.QuotationMilenioLiberty.InfoRequest infoRequest;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://libertytypes.com.iaxis.services", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute("preguntaPoliza", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Servicios.QuotationMilenioLiberty.PreguntaGeneral[] preguntaPoliza;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://libertytypes.com.iaxis.services", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute("preguntaRiesgo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Servicios.QuotationMilenioLiberty.PreguntaGeneral[] preguntaRiesgo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://libertytypes.com.iaxis.services", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute("preguntaTablaRiesgo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Servicios.QuotationMilenioLiberty.PreguntaTablaGeneral[] preguntaTablaRiesgo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://libertytypes.com.iaxis.services", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute("preguntaTablaPoliza", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Servicios.QuotationMilenioLiberty.PreguntaTablaGeneral[] preguntaTablaPoliza;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://libertytypes.com.iaxis.services", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute("tomadorPersonaJuridica", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Servicios.QuotationMilenioLiberty.PersonaJuridica[] tomadorPersonaJuridica;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://libertytypes.com.iaxis.services", Order=10)]
        [System.Xml.Serialization.XmlElementAttribute("tomadorPersonaNatural", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Servicios.QuotationMilenioLiberty.PersonaNatural[] tomadorPersonaNatural;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://libertytypes.com.iaxis.services", Order=11)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Servicios.QuotationMilenioLiberty.Usuario usuario;
        
        public quotationCarGenericRequest() {
        }
        
        public quotationCarGenericRequest(Servicios.QuotationMilenioLiberty.Amparo[] amparo, Servicios.QuotationMilenioLiberty.Automovil automovil, Servicios.QuotationMilenioLiberty.PersonaNatural conductor, Servicios.QuotationMilenioLiberty.DatosGestion datosGestion, Servicios.QuotationMilenioLiberty.InfoRequest infoRequest, Servicios.QuotationMilenioLiberty.PreguntaGeneral[] preguntaPoliza, Servicios.QuotationMilenioLiberty.PreguntaGeneral[] preguntaRiesgo, Servicios.QuotationMilenioLiberty.PreguntaTablaGeneral[] preguntaTablaRiesgo, Servicios.QuotationMilenioLiberty.PreguntaTablaGeneral[] preguntaTablaPoliza, Servicios.QuotationMilenioLiberty.PersonaJuridica[] tomadorPersonaJuridica, Servicios.QuotationMilenioLiberty.PersonaNatural[] tomadorPersonaNatural, Servicios.QuotationMilenioLiberty.Usuario usuario) {
            this.amparo = amparo;
            this.automovil = automovil;
            this.conductor = conductor;
            this.datosGestion = datosGestion;
            this.infoRequest = infoRequest;
            this.preguntaPoliza = preguntaPoliza;
            this.preguntaRiesgo = preguntaRiesgo;
            this.preguntaTablaRiesgo = preguntaTablaRiesgo;
            this.preguntaTablaPoliza = preguntaTablaPoliza;
            this.tomadorPersonaJuridica = tomadorPersonaJuridica;
            this.tomadorPersonaNatural = tomadorPersonaNatural;
            this.usuario = usuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="quotationCarGenericRs", WrapperNamespace="http://libertytypes.com.iaxis.services", IsWrapped=true)]
    public partial class quotationCarGenericResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://libertytypes.com.iaxis.services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Servicios.QuotationMilenioLiberty.InfoResponse infoResponse;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://libertytypes.com.iaxis.services", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Servicios.QuotationMilenioLiberty.ElementoCodificado simulacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://libertytypes.com.iaxis.services", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Servicios.QuotationMilenioLiberty.DatosGestion datosGestion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://libertytypes.com.iaxis.services", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute("amparo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Servicios.QuotationMilenioLiberty.Amparo[] amparo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://libertytypes.com.iaxis.services", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Servicios.QuotationMilenioLiberty.Prima datosEconomicos;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://libertytypes.com.iaxis.services", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute("PSU", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Servicios.QuotationMilenioLiberty.PSU[] PSU;
        
        public quotationCarGenericResponse() {
        }
        
        public quotationCarGenericResponse(Servicios.QuotationMilenioLiberty.InfoResponse infoResponse, Servicios.QuotationMilenioLiberty.ElementoCodificado simulacion, Servicios.QuotationMilenioLiberty.DatosGestion datosGestion, Servicios.QuotationMilenioLiberty.Amparo[] amparo, Servicios.QuotationMilenioLiberty.Prima datosEconomicos, Servicios.QuotationMilenioLiberty.PSU[] PSU) {
            this.infoResponse = infoResponse;
            this.simulacion = simulacion;
            this.datosGestion = datosGestion;
            this.amparo = amparo;
            this.datosEconomicos = datosEconomicos;
            this.PSU = PSU;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface QuotationCarGenericPortTypeChannel : Servicios.QuotationMilenioLiberty.QuotationCarGenericPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QuotationCarGenericPortTypeClient : System.ServiceModel.ClientBase<Servicios.QuotationMilenioLiberty.QuotationCarGenericPortType>, Servicios.QuotationMilenioLiberty.QuotationCarGenericPortType {
        
        public QuotationCarGenericPortTypeClient() {
        }
        
        public QuotationCarGenericPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QuotationCarGenericPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QuotationCarGenericPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QuotationCarGenericPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Servicios.QuotationMilenioLiberty.quotationCarGenericResponse Servicios.QuotationMilenioLiberty.QuotationCarGenericPortType.quotationCarGeneric(Servicios.QuotationMilenioLiberty.quotationCarGenericRequest request) {
            return base.Channel.quotationCarGeneric(request);
        }
        
        public Servicios.QuotationMilenioLiberty.InfoResponse quotationCarGeneric(ref Servicios.QuotationMilenioLiberty.Amparo[] amparo, Servicios.QuotationMilenioLiberty.Automovil automovil, Servicios.QuotationMilenioLiberty.PersonaNatural conductor, ref Servicios.QuotationMilenioLiberty.DatosGestion datosGestion, Servicios.QuotationMilenioLiberty.InfoRequest infoRequest, Servicios.QuotationMilenioLiberty.PreguntaGeneral[] preguntaPoliza, Servicios.QuotationMilenioLiberty.PreguntaGeneral[] preguntaRiesgo, Servicios.QuotationMilenioLiberty.PreguntaTablaGeneral[] preguntaTablaRiesgo, Servicios.QuotationMilenioLiberty.PreguntaTablaGeneral[] preguntaTablaPoliza, Servicios.QuotationMilenioLiberty.PersonaJuridica[] tomadorPersonaJuridica, Servicios.QuotationMilenioLiberty.PersonaNatural[] tomadorPersonaNatural, Servicios.QuotationMilenioLiberty.Usuario usuario, out Servicios.QuotationMilenioLiberty.ElementoCodificado simulacion, out Servicios.QuotationMilenioLiberty.Prima datosEconomicos, out Servicios.QuotationMilenioLiberty.PSU[] PSU) {
            Servicios.QuotationMilenioLiberty.quotationCarGenericRequest inValue = new Servicios.QuotationMilenioLiberty.quotationCarGenericRequest();
            inValue.amparo = amparo;
            inValue.automovil = automovil;
            inValue.conductor = conductor;
            inValue.datosGestion = datosGestion;
            inValue.infoRequest = infoRequest;
            inValue.preguntaPoliza = preguntaPoliza;
            inValue.preguntaRiesgo = preguntaRiesgo;
            inValue.preguntaTablaRiesgo = preguntaTablaRiesgo;
            inValue.preguntaTablaPoliza = preguntaTablaPoliza;
            inValue.tomadorPersonaJuridica = tomadorPersonaJuridica;
            inValue.tomadorPersonaNatural = tomadorPersonaNatural;
            inValue.usuario = usuario;
            Servicios.QuotationMilenioLiberty.quotationCarGenericResponse retVal = ((Servicios.QuotationMilenioLiberty.QuotationCarGenericPortType)(this)).quotationCarGeneric(inValue);
            simulacion = retVal.simulacion;
            datosGestion = retVal.datosGestion;
            amparo = retVal.amparo;
            datosEconomicos = retVal.datosEconomicos;
            PSU = retVal.PSU;
            return retVal.infoResponse;
        }
        
        public System.Threading.Tasks.Task<Servicios.QuotationMilenioLiberty.quotationCarGenericResponse> quotationCarGenericAsync(Servicios.QuotationMilenioLiberty.quotationCarGenericRequest request) {
            return base.Channel.quotationCarGenericAsync(request);
        }
    }
}
